### PR TITLE
Update funcs.ts to use relative path of jupyter server

### PR DESCRIPTION
**Pull request by bsatoriu**

### CODE REVIEW

**Comment by grallewellyn** [comment]
Is there an image I can use to test this?

**Comment by bsatoriu** [comment]
Not yet @grallewellyn--what's the process for publishing these extensions for testing?

**Comment by grallewellyn** [comment]
I can do it. The testing steps are:
1. Run through the README commands again after making your changes (I still need to test if you need to run through all of them, but I think it is more than just `jlpm build`) 
2. `sudo python -m build` in the extension (might need to do `python3 -m pip install --upgrade build` first). 
3. Add the whl file to the jupyterlab folder and add these lines to maap-workspaces and build locally: 
```
COPY ./maap_help_jupyter_extension-1.2.1-py3-none-any.whl /maap_help_jupyter_extension-1.2.1-py3-none-any.whl
RUN source activate $WORKSPACE_TYPE && \
    pip install /maap_help_jupyter_extension-1.2.1-py3-none-any.whl
```
Remember to comment out the extension install from the environment.yml
4. Publish that image and test in DIT

Alternatively, I just tried testing this by installing it directly in an already running DIT workspace, but the extension doesn't correctly uninstall in the first place, so I don't think that is the best way to test

**Comment by grallewellyn** [comment]
@bsatoriu Are you able to successfully run through the README commands? I am getting errors
Screenshot 2024-07-24 at 9 17 24 AM
Screenshot 2024-07-24 at 9 17 38 AM

**Comment by bsatoriu** [comment]
Sorry @grallewellyn, I fixed the compile errors. Would you please try once more?

**Comment by grallewellyn** [comment]
Yep, it works now! I am building the image to test now
https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/7055

**Comment by grallewellyn** [comment]
I tested with this image: mas.dit.maap-project.org/root/maap-workspaces/jupyterlab/python:presignedUrl-relative-path-1036
And I still can't get the presigned s3 url

**Review by grallewellyn — APPROVED** [review]
Approving because with the image 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab/python:presignedUrl-relative-path-1036' I can get presigned s3 urls
We merged in the jupyterlab 4 updates to fix one of the bugs that came up as well

**Pull request merged**
